### ISSUE TITLE
Hydration error with uploaded projects

### ISSUE THREAD

**Issue by robynstuart** [optimamodel/Optima#774]
To replicate:

1. Upload file https://drive.google.com/folderview?id=0BysN_-IUZuYBRFlDb2liZFVTdUE&usp=sharing to FE
2. Navigate to Define programs -> Define cost and outcome functions
3. Select a program from the drop-down list

_Expected behaviour_
Page should load with graph at left, table & data at right

_Actual behaviour_
Error message as below

```
Traceback (most recent call last):
  File "/opt/optima/server/webapp/utils.py", line 63, in _report_exception
    return api_call(*args, **kwargs)
  File "/opt/optima/server/webapp/resources/project_progsets.py", line 352, in get
    result_instance = result_entry.hydrate()  # TODO raise exception if none
AttributeError: 'NoneType' object has no attribute 'hydrate'
```

**Comment by boscoh** [comment]
Fixed in PR https://github.com/optimamodel/Optima/pull/778
