### ISSUE TITLE
Save scenarios automatically

### ISSUE THREAD

**Issue by cliffckerr** [optimamodel/Optima#776]
1) Upload a project, e.g. http://optimamodel.com/dump/default.prj [NB, try out that folder!]
2) Go to scenarios
3) Create a parameter scenario, enter the name and select the parameter set
4) Click "Run"
EXPECTED: It works
ACTUAL: It doesn't
SOLUTION: Make the "Run" button execute the "Save" function first.
Bonus points: for all drop-down menus, have the first item selected by default (instead of none)

**Comment by boscoh** [comment]
See PR https://github.com/optimamodel/Optima/pull/778

**Comment by boscoh** [comment]
Fixed in https://github.com/optimamodel/Optima/pull/778
