### ISSUE TITLE
Manual fitting broken

### ISSUE THREAD

**Issue by cliffckerr** [optimamodel/Optima#797]
Latest merge seems to have broken manual fitting:
```
>>> P.manualfit()
    Structure list already has item named "manualfit"
    parset "default" copied to "manualfit"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Anna\cliff\optima\optima\project.py", line 420, in manualfit
    manualfit(project=self, name=name, ind=ind, verbose=verbose) # Actually run manual fitting
  File "C:\Users\Anna\cliff\optima\optima\gui.py", line 332, in manualfit
    mflists = parset.manualfitlists()
AttributeError: 'Parameterset' object has no attribute 'manualfitlists'
```

**Comment by boscoh** [comment]
Does this PR fix the bug: https://github.com/optimamodel/Optima/pull/799 ?

Sorry about that, based on our earlier conversation, I thought that `manualfitlist` and `update` were written by SSQ and not used in gui.py, so I moved and cleaned them up to `server/webapp/parse.py`. I should have checked in `gui.py`, which sadly, I can't get working yet on my mac.

**Comment by Rowanmh** [comment]
Hi @boscoh @cliffckerr - what do you mean by manual fitting?  Just testing on staging.optimamodel.com and manual calibration seems okay.  Or is this a newer PR?

**Comment by boscoh** [comment]
@Rowanmh it's for `gui.py` in the main optima directory.
